name: Laravel CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: Install MySQL
        run: |
          sudo apt update
          sudo apt install -y mysql-server

      - name: Start MySQL Service
        run: |
          sudo service mysql start

      - name: Create Database and User
        run: |
          sudo mysql -u root -e "CREATE DATABASE akhil;"
          sudo mysql -u root -e "CREATE USER 'akhil'@'localhost' IDENTIFIED BY 'password';"
          sudo mysql -u root -e "GRANT ALL PRIVILEGES ON akhil.* TO 'akhil'@'localhost';"
          sudo mysql -u root -e "FLUSH PRIVILEGES;"
      - name: Install Composer Dependencies
        run: composer install

      - name: Copy Environment File
        run: cp .env.example .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Run PHPUnit Tests
        run: ./vendor/bin/phpunit

      - name: Migrate database
        run: php artisan migrate

