name: Laravel CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
          MYSQL_DATABASE: akhil
          MYSQL_USER: root
          MYSQL_PASSWORD: password

    steps:
      - name: Show Docker containers
        run: docker ps -a

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: Install MySQL
        run: |
          sudo apt update
          sudo apt install -y mysql-server

      - name: Start MySQL Service
        run: |
          sudo service mysql start

      - name: Install Composer Dependencies
        run: composer install

      - name: Copy Environment File
        run: cp .env.example .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Run PHPUnit Tests
        run: ./vendor/bin/phpunit

      - name: Migrate database
        run: php artisan migrate

